package saqs.eis;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.junit.Assert.*;

public class ServerTest {
    @Test public void server_start() {
        Server server = new Server();
        server.start();
    }
}
